name: Build

on:
  push:
  pull_request:
  release:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Update repository
        run: |
          sudo apt-fast update

      - name: Install depend packages
        run: |
          sudo apt-fast install -y liballegro5-dev
          sudo apt-fast install -y libstb-dev
          sudo apt-fast install -y libfreetype-dev
          sudo apt-fast install -y cmake make
          sudo apt-fast install -y gcc g++ git

      - name: Get submodules
        run: |
          git submodule init
          git pull --recurse-submodules

      - name: Create MakeFile
        run: cmake .

      - name: Make
        run: make