name: Build

on:
  push:
  pull_request:
  release:

env:
  BUILD_TYPE: Release

jobs:
  build:
    container: debian:bullseye
    steps:

      - uses: actions/checkout@v2

      - name: Update repository
        run: apt update

      - name: Install depend packages
        run: |
          apt install -y libimgui-dev
          apt install -y liballegro5-dev
          apt install -y libstb-dev
          apt install -y cmake make
          apt install -y gcc g++

      - name: Create MakeFile
        run: cmake .

      - name: Make
        run: make